"""
chart.py — Conversion of .chart (Clone Hero / Moonscraper) to MIDI (RB/CH).

Downcharter works on MIDI (it generates difficulties, venue, animations, talkies).
To support songs in .chart we first convert them to a MidiFile in the standard
RB/CH layout and then run them through the normal pipeline:

  .chart  →  chart_to_midi()  →  mido.MidiFile  →  process_midi(...)

Main mappings (.chart → MIDI Expert):
  • [SyncTrack]  B <bpm*1000>  → set_tempo ;  TS <num> [<den_pow>] → time_signature
  • [Events]     E "section X" → EVENTS  text "[section X]"
                 E "lyric ...", "phrase_start/end" → PART VOCALS (lyrics + markers 105)
  • Instrument (highest difficulty present, placed in the Expert range):
      N 0-4 → frets G..O (96-100) ;  N 7 → open (95) ;  sustain = length
      N 5 (forced) → force HOPO/strum (101/102, via the natural state)
      S 2 (star power) → 116 ;  E solo/soloend → 103
  • Drums: N 0 kick→96, 1→97, 2→98, 3→99, 4→100 ;  N 32 (2x kick)→95
      tom markers 110/111/112 for yellow/blue/green WITHOUT a cymbal marker (66/67/68)

Only the highest difficulty of each instrument is converted — the lower ones are
generated by Downcharter from the Expert (same as the MIDI flow).
"""
from __future__ import annotations
import os
import re
import mido

# ── Instrument / difficulty maps ──────────────────────────────────────────────

# .chart section suffix → (PART track name, is_drums)
_INSTRUMENTS = {
    "Single":       ("PART GUITAR", False),
    "DoubleGuitar": ("PART GUITAR COOP", False),
    "DoubleBass":   ("PART BASS", False),
    "DoubleRhythm": ("PART RHYTHM", False),
    "Keyboard":     ("PART KEYS", False),
    "Drums":        ("PART DRUMS", True),
}
_DIFFS = ["Expert", "Hard", "Medium", "Easy"]   # preference order

EXPERT_BASE = 96            # Green Expert
OPEN_NOTE   = 95
FORCE_ON    = 101           # force HOPO
FORCE_OFF   = 102           # force strum
STARPOWER   = 116
SOLO        = 103
KICK        = 96
KICK_2X     = 95
DRUM_PAD = {0: 96, 1: 97, 2: 98, 3: 99, 4: 100, 5: 100}   # kick,R,Y,B,G(+5lane G)
DRUM_TOM_MARKER = {2: 110, 3: 111, 4: 112}                # yellow/blue/green tom
DRUM_CYMBAL_FLAG = {66: 2, 67: 3, 68: 4}                  # cymbal → cancels tom
# Drum dynamics flags (Clone Hero .chart): pad index + offset, mirroring the
# cymbal pad+64 scheme. Accent pad+33 (33=kick..37=green), ghost pad+39
# (39=kick..43=green). In the .mid these become note velocities (read by
# YARG/CH only when the track is flagged [ENABLE_CHART_DYNAMICS]).
DRUM_ACCENT_OFFSET = 33
DRUM_GHOST_OFFSET  = 39
DRUM_FILL_NOTES = (120, 121, 122, 123, 124)   # RB/YARG drum activation fill (all 5)
VEL_NORMAL = 100
VEL_ACCENT = 127
VEL_GHOST  = 1

_LINE_RE = re.compile(r"^\s*([0-9]+)\s*=\s*(\w+)\s+(.*?)\s*$")


# ── Parsing ───────────────────────────────────────────────────────────────────

def is_chart(path: str) -> bool:
    return path.lower().endswith(".chart")


def _parse(path: str) -> tuple[dict, dict]:
    """Read the .chart → (meta[Song], sections{name: [(tick, type, args_str)]})."""
    with open(path, encoding="utf-8-sig", errors="ignore") as f:
        text = f.read()
    meta: dict[str, str] = {}
    sections: dict[str, list[tuple[int, str, str]]] = {}
    cur: str | None = None
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("[") and line.endswith("]"):
            cur = line[1:-1].strip()
            sections.setdefault(cur, [])
            continue
        if line == "{" or line == "}":
            continue
        if cur == "Song":
            if "=" in line:
                k, v = line.split("=", 1)
                meta[k.strip()] = v.strip().strip('"')
            continue
        m = _LINE_RE.match(line)
        if m and cur is not None:
            tick = int(m.group(1))
            typ = m.group(2)
            args = m.group(3)
            sections[cur].append((tick, typ, args))
    return meta, sections


# ── MIDI construction ─────────────────────────────────────────────────────────

def _track_from_events(name: str, events: list[tuple[int, mido.Message]]) -> mido.MidiTrack:
    """Build a MidiTrack from (abs_tick, msg) — sorts and computes deltas."""
    tr = mido.MidiTrack()
    tr.name = name
    events.sort(key=lambda e: (e[0], 0 if e[1].type == "note_off" else 1))
    prev = 0
    for tick, msg in events:
        tr.append(msg.copy(time=tick - prev))
        prev = tick
    tr.append(mido.MetaMessage("end_of_track", time=0))
    return tr


def _sync_track(sync: list[tuple[int, str, str]]) -> mido.MidiTrack:
    evs: list[tuple[int, mido.Message]] = []
    for tick, typ, args in sync:
        toks = args.split()
        if typ == "B" and toks:                    # BPM*1000
            bpm = int(toks[0]) / 1000.0
            tempo = int(round(60_000_000 / bpm)) if bpm > 0 else 500_000
            evs.append((tick, mido.MetaMessage("set_tempo", tempo=tempo, time=0)))
        elif typ == "TS" and toks:                 # numerator [den_pow]
            num = int(toks[0])
            den = 2 ** int(toks[1]) if len(toks) > 1 else 4
            evs.append((tick, mido.MetaMessage(
                "time_signature", numerator=num, denominator=den, time=0)))
    if not any(m.type == "set_tempo" for _, m in evs):
        evs.append((0, mido.MetaMessage("set_tempo", tempo=500_000, time=0)))
    return _track_from_events("TEMPO", evs)


def _events_and_vocals(events: list[tuple[int, str, str]]) -> tuple[mido.MidiTrack, mido.MidiTrack | None]:
    """Global [Events] → EVENTS ([section ..]) + PART VOCALS (lyrics/phrases)."""
    ev_evs: list[tuple[int, mido.Message]] = []
    voc_evs: list[tuple[int, mido.Message]] = []
    phrase_open: int | None = None
    last_lyric = 0
    for tick, typ, args in events:
        if typ != "E":
            continue
        txt = args.strip().strip('"').strip()
        low = txt.lower()
        if low.startswith("section ") or low.startswith("prc_"):
            name = txt[8:] if low.startswith("section ") else txt
            ev_evs.append((tick, mido.MetaMessage("text", text=f"[section {name}]", time=0)))
        elif low.startswith("lyric"):
            syl = txt[5:].strip() or "+"
            voc_evs.append((tick, mido.MetaMessage("lyrics", text=syl, time=0)))
            last_lyric = max(last_lyric, tick)
        elif low == "phrase_start":
            if phrase_open is not None:
                voc_evs.append((phrase_open, mido.Message("note_on", note=105, velocity=96, time=0)))
                voc_evs.append((tick, mido.Message("note_off", note=105, velocity=0, time=0)))
            phrase_open = tick
        elif low == "phrase_end":
            if phrase_open is not None:
                voc_evs.append((phrase_open, mido.Message("note_on", note=105, velocity=96, time=0)))
                voc_evs.append((tick, mido.Message("note_off", note=105, velocity=0, time=0)))
                phrase_open = None
        else:
            # other global events (e.g. [music_start], [end]) → literal EVENTS
            ev_evs.append((tick, mido.MetaMessage("text", text=f"[{txt}]", time=0)))
    if phrase_open is not None:                    # phrase left open until the last lyric
        end = max(last_lyric + 1, phrase_open + 1)
        voc_evs.append((phrase_open, mido.Message("note_on", note=105, velocity=96, time=0)))
        voc_evs.append((end, mido.Message("note_off", note=105, velocity=0, time=0)))
    ev_tr = _track_from_events("EVENTS", ev_evs)
    voc_tr = _track_from_events("PART VOCALS", voc_evs) if voc_evs else None
    return ev_tr, voc_tr


def _highest_diff(sections: dict, suffix: str) -> str | None:
    for d in _DIFFS:
        key = d + suffix
        if sections.get(key):
            return key
    return None


def _gems_by_tick(lines: list[tuple[int, str, str]], is_drums: bool):
    """Group the N/S/E of an instrument section by tick.
    The lane semantics differ between 5-fret and drums (e.g. N 5 = forced on
    5-fret, but green-5lane on drums).
    Returns (gems{tick: dict}, sp[(t,len)], solos[(t,'solo'/'soloend')],
    fills[(t,len)] — drum activation fills, S 64)."""
    gems: dict[int, dict] = {}
    sp: list[tuple[int, int]] = []
    solos: list[tuple[int, str]] = []
    fills: list[tuple[int, int]] = []
    for tick, typ, args in lines:
        toks = args.split()
        if typ == "N" and len(toks) >= 2:
            lane, length = int(toks[0]), int(toks[1])
            g = gems.setdefault(tick, {"frets": set(), "open": False,
                                       "forced": False, "tap": False,
                                       "len": 0, "cymbals": set(), "kick2x": False,
                                       "accent": set(), "ghost": set()})
            if is_drums:
                if lane in (0, 1, 2, 3, 4, 5):
                    g["frets"].add(lane)
                elif lane == 32:
                    g["kick2x"] = True
                elif lane in DRUM_CYMBAL_FLAG:
                    g["cymbals"].add(DRUM_CYMBAL_FLAG[lane])
                elif DRUM_ACCENT_OFFSET <= lane <= DRUM_ACCENT_OFFSET + 4:
                    g["accent"].add(lane - DRUM_ACCENT_OFFSET)   # pad index 0..4
                elif DRUM_GHOST_OFFSET <= lane <= DRUM_GHOST_OFFSET + 4:
                    g["ghost"].add(lane - DRUM_GHOST_OFFSET)     # pad index 0..4
            else:
                if lane in (0, 1, 2, 3, 4):
                    g["frets"].add(lane); g["len"] = max(g["len"], length)
                elif lane == 7:
                    g["open"] = True; g["len"] = max(g["len"], length)
                elif lane == 5:                    # forced flag
                    g["forced"] = True
                elif lane == 6:                    # tap flag
                    g["tap"] = True
        elif typ == "S" and len(toks) >= 2 and toks[0] == "2":
            sp.append((tick, int(toks[1])))
        elif typ == "S" and len(toks) >= 2 and toks[0] == "64":
            fills.append((tick, int(toks[1])))   # drum activation fill
        elif typ == "E":
            name = args.strip().strip('"').lower()
            if name in ("solo", "soloend"):
                solos.append((tick, name))
    return gems, sp, solos, fills


def _guitar_track(name: str, lines, tpb: int) -> mido.MidiTrack:
    gems, sp, solos, _fills = _gems_by_tick(lines, is_drums=False)
    hopo_thresh = max(1, tpb // 3)
    evs: list[tuple[int, mido.Message]] = []
    prev_tick = -10 ** 9
    prev_frets: frozenset[int] = frozenset()
    has_open = False
    for tick in sorted(gems):
        g = gems[tick]
        frets = frozenset(f for f in g["frets"] if f <= 4)
        length = g["len"]
        end = tick + (length if length > 0 else 1)
        if g["open"]:
            has_open = True
            evs.append((tick, mido.Message("note_on", note=OPEN_NOTE, velocity=100, time=0)))
            evs.append((end, mido.Message("note_off", note=OPEN_NOTE, velocity=0, time=0)))
            cur = frozenset({-1})
        else:
            for f in sorted(frets):
                evs.append((tick, mido.Message("note_on", note=EXPERT_BASE + f, velocity=100, time=0)))
                evs.append((end, mido.Message("note_off", note=EXPERT_BASE + f, velocity=0, time=0)))
            cur = frets
        # Natural HOPO (single, different fret, short gap) — forced inverts; tap forces HOPO.
        single = len(cur) == 1 and not g["open"]
        natural = single and cur != prev_frets and (tick - prev_tick) <= hopo_thresh
        desired = (not natural) if g["forced"] else natural
        if g["tap"]:
            desired = True
        if desired and not natural:
            evs.append((tick, mido.Message("note_on", note=FORCE_ON, velocity=100, time=0)))
            evs.append((tick + 1, mido.Message("note_off", note=FORCE_ON, velocity=0, time=0)))
        elif natural and not desired:
            evs.append((tick, mido.Message("note_on", note=FORCE_OFF, velocity=100, time=0)))
            evs.append((tick + 1, mido.Message("note_off", note=FORCE_OFF, velocity=0, time=0)))
        prev_tick, prev_frets = tick, cur
    _add_sp_solo(evs, sp, solos)
    # Opens are charted as the note one below green (95/83/71/59 = "ENHANCED_OPENS").
    # YARG/Clone Hero/Moonscraper only read that below-green note as an open strum if
    # the track is flagged with a `[ENHANCED_OPENS]` text event — without it they
    # silently drop the note (the open notes "disappear" in-game). Emit it at tick 0.
    if has_open:
        evs.append((0, mido.MetaMessage("text", text="[ENHANCED_OPENS]", time=0)))
    return _track_from_events(name, evs)


def _map_drum_lane(lane: int, frets: set[int], five_lane: bool) -> tuple[int | None, int | None]:
    """Map a .chart drum lane → (RB pad note, tom-marker note or None).

    4-lane (Pro) charts pass through unchanged: 0..4 → kick/R/Y/B/G, with
    yellow/blue/green getting a tom marker (110/111/112) so they default to toms.

    5-lane (GH) charts must FOLD orange(4)+green(5) into RB's single green lane.
    Both naively mapped to green (100) → simultaneous orange+green LOSES a note.
    Onyx-style collision-free fold:
      • orange(4) → green (100), a cymbal (no tom marker)
      • green(5)  → green (100) normally, but → blue (99) when orange is also hit
                    at the same tick (a tom). yellow(2)/orange(4) are cymbals,
                    blue(3)/green(5) are toms (GH kit convention).
    Returns (None, None) for lanes that aren't pads (handled elsewhere)."""
    if not five_lane:
        pad = DRUM_PAD.get(lane)
        tom = DRUM_TOM_MARKER.get(lane)
        return pad, tom
    # 5-lane GH fold
    if lane == 0:
        return 96, None                       # kick
    if lane == 1:
        return 97, None                       # red / snare
    if lane == 2:
        return 98, None                       # yellow → cymbal (no tom marker)
    if lane == 3:
        return 99, 111                        # blue → tom
    if lane == 4:
        return 100, None                      # orange → green cymbal (no tom marker)
    if lane == 5:                             # green
        if 4 in frets:                        # orange also hit → move green to blue tom
            return 99, 111
        return 100, 112                       # green tom
    return None, None


def _drums_track(name: str, lines, tpb: int) -> mido.MidiTrack:
    gems, sp, solos, fills = _gems_by_tick(lines, is_drums=True)
    five_lane = any(5 in g["frets"] for g in gems.values())
    has_dynamics = any(g["accent"] or g["ghost"] for g in gems.values())
    evs: list[tuple[int, mido.Message]] = []
    for tick in sorted(gems):
        g = gems[tick]
        end = tick + 1
        if g["kick2x"]:
            evs.append((tick, mido.Message("note_on", note=KICK_2X, velocity=VEL_NORMAL, time=0)))
            evs.append((end, mido.Message("note_off", note=KICK_2X, velocity=0, time=0)))
        emitted: set[int] = set()             # RB pads already placed at this tick
        for lane in sorted(g["frets"]):
            pad, tom = _map_drum_lane(lane, g["frets"], five_lane)
            if pad is None or pad in emitted:  # skip true duplicates (never silent loss)
                continue
            emitted.add(pad)
            # Ghost/accent → note velocity (read by YARG/CH under [ENABLE_CHART_DYNAMICS]).
            if lane in g["ghost"]:
                vel = VEL_GHOST
            elif lane in g["accent"]:
                vel = VEL_ACCENT
            else:
                vel = VEL_NORMAL
            evs.append((tick, mido.Message("note_on", note=pad, velocity=vel, time=0)))
            evs.append((end, mido.Message("note_off", note=pad, velocity=0, time=0)))
            # 4-lane: explicit chart cymbal flag (66/67/68) cancels the default tom.
            if tom is not None and not (not five_lane and lane in g["cymbals"]):
                evs.append((tick, mido.Message("note_on", note=tom, velocity=VEL_NORMAL, time=0)))
                evs.append((end, mido.Message("note_off", note=tom, velocity=0, time=0)))
    _add_sp_solo(evs, sp, solos)
    # Drum activation fills (.chart S 64) → RB/YARG fill lanes 120-124 across the span.
    for t, length in fills:
        fend = t + max(1, length)
        for fn in DRUM_FILL_NOTES:
            evs.append((t, mido.Message("note_on", note=fn, velocity=VEL_NORMAL, time=0)))
            evs.append((fend, mido.Message("note_off", note=fn, velocity=0, time=0)))
    # Per-note ghost/accent velocities are only honored by YARG/Clone Hero when the
    # drum track is flagged [ENABLE_CHART_DYNAMICS]; otherwise dynamics are dropped.
    if has_dynamics:
        evs.append((0, mido.MetaMessage("text", text="[ENABLE_CHART_DYNAMICS]", time=0)))
    return _track_from_events(name, evs)


def _add_sp_solo(evs, sp, solos):
    for t, length in sp:
        evs.append((t, mido.Message("note_on", note=STARPOWER, velocity=100, time=0)))
        evs.append((t + max(1, length), mido.Message("note_off", note=STARPOWER, velocity=0, time=0)))
    open_solo: int | None = None
    for t, kind in sorted(solos):
        if kind == "solo":
            open_solo = t
        elif kind == "soloend" and open_solo is not None:
            evs.append((open_solo, mido.Message("note_on", note=SOLO, velocity=100, time=0)))
            evs.append((t, mido.Message("note_off", note=SOLO, velocity=0, time=0)))
            open_solo = None


def chart_to_midi(path: str) -> mido.MidiFile:
    """Convert a .chart into a mido.MidiFile (RB/CH layout, highest difficulty)."""
    meta, sections = _parse(path)
    tpb = int(meta.get("Resolution", "192"))
    mid = mido.MidiFile(type=1, ticks_per_beat=tpb)

    mid.tracks.append(_sync_track(sections.get("SyncTrack", [])))

    ev_tr, voc_tr = _events_and_vocals(sections.get("Events", []))
    mid.tracks.append(ev_tr)

    for suffix, (track_name, is_drums) in _INSTRUMENTS.items():
        key = _highest_diff(sections, suffix)
        if not key:
            continue
        lines = sections[key]
        if is_drums:
            mid.tracks.append(_drums_track(track_name, lines, tpb))
        else:
            mid.tracks.append(_guitar_track(track_name, lines, tpb))

    if voc_tr is not None:
        mid.tracks.append(voc_tr)

    return mid
