"""validate.py — pre-pack sanity gate for the RB3 MIDI (PS3 / Xbox builds only).

Magma runs a long list of MIDI checks before it compiles a song; some are pure
pedantry (track-name conventions, density warnings) but a handful guard against
things that genuinely **crash Rock Band 3 in-game**. We do NOT want to run Magma,
but we DO want its crash-relevant guarantees on the notes.mid we ship.

This module is deliberately scoped to the PACK step (ps3build / stfs) — never the
Process tab. Processing reduces/charts freely; only when we assemble the final
console package do we assert the result is something RB3 will load without
crashing. Every check is NON-FATAL by default (it returns a list of issues the
caller logs, like quality.groove_check), so a questionable chart still builds —
the user just gets warned. Callers may choose to treat "error" issues as fatal.

Crash-relevant checks implemented (see the study in CLAUDE/chat):
  * time division must be 480 TPB
  * every charted gem difficulty (Easy/Med/Hard/Expert) must be non-empty
  * no stuck/overlapping note of the same pitch on one track (broken-chord / hung
    sustain — RB3 can hang drawing it)
  * a missing [end] event (characters freeze in slow-mo at the end)
  * BEAT track present with >= 2 beats of lead-in before the first gem
  * PART VOCALS: notes must sit inside a phrase marker, phrases must not overlap
"""
from __future__ import annotations

import re

import mido

from .midi_utils import to_abs

# Regex shared with venue.py for section markers in the EVENTS track.
_SECTION_RE = re.compile(r"\[\s*section\s+(.+?)\s*\]|\[\s*prc_(.+?)\s*\]")

# Regex for extracting PP filter name from VENUE text events.
_PP_RE = re.compile(r"^\[(.+)\.pp\]$")

# Regex for extracting directed cut name from VENUE text events.
_DIRECTED_RE = re.compile(r"^\[(directed_.+)\]$")

# Per-difficulty gem pitch windows, shared by guitar/bass/keys/drums.
_DIFF_WINDOWS = {
    "Easy":   (60, 64),
    "Medium": (72, 76),
    "Hard":   (84, 88),
    "Expert": (96, 100),
}
# PART tracks that use the 4-difficulty gem windows above.
_GEM_PARTS = ("PART GUITAR", "PART BASS", "PART DRUMS", "PART KEYS",
              "PART RHYTHM", "PART GUITAR COOP")

# Vocal phrase markers and the talky/sung pitch band of PART VOCALS.
_VOCAL_PHRASE = (105, 106)
_VOCAL_MIN, _VOCAL_MAX = 36, 84

# Baseline spam metrics measured from 30 official RB3 venue MIDIs.
# Used internally to compare Downcharter output against the official envelope.
# Generated by dev/_spam_baseline.py on 2026-07-03.
_SPAM_BASELINE: dict[str, dict[str, float]] = {
    "pp_events_per_section":    {"p25": 1, "p50": 3, "p75": 7},
    "pp_filters_per_section":   {"p25": 1, "p50": 2, "p75": 3},
    "directed_consecutive_pct": {"p25": 0.172, "p50": 0.217, "p75": 0.292},
}


def _is_on(m) -> bool:
    return m.type == "note_on" and getattr(m, "velocity", 0) > 0


def _is_off(m) -> bool:
    return m.type == "note_off" or (m.type == "note_on"
                                    and getattr(m, "velocity", 0) == 0)


def _first_gem_tick(mid) -> int | None:
    """Earliest tick of any Expert gem across the instrument tracks."""
    lo, hi = _DIFF_WINDOWS["Expert"]
    best = None
    for tr in mid.tracks:
        nm = (tr.name or "").upper()
        if not any(nm.startswith(p) for p in _GEM_PARTS):
            continue
        for e in to_abs(tr):
            if _is_on(e.msg) and lo <= e.msg.note <= hi:
                best = e.abs_tick if best is None else min(best, e.abs_tick)
                break
    return best


def _check_overlaps(tr, name, issues):
    """Flag a same-pitch note_on arriving while that pitch is still held (a stuck
    sustain). RB3 can hang trying to render the never-closed gem."""
    open_pitch: dict[int, int] = {}
    bad = 0
    # Process note-offs before note-ons at the same tick so a back-to-back
    # gem (off then on at the identical tick) is NOT mistaken for an overlap.
    evts = sorted(to_abs(tr), key=lambda e: (e.abs_tick, 0 if _is_off(e.msg) else 1))
    for e in evts:
        m = e.msg
        n = getattr(m, "note", None)
        if n is None:
            continue
        if _is_on(m):
            if n in open_pitch:
                bad += 1
            open_pitch[n] = e.abs_tick
        elif _is_off(m):
            open_pitch.pop(n, None)
    if bad:
        issues.append(("error",
                       f"{name}: {bad} overlapping/stuck note(s) of the same "
                       f"pitch (broken chord / hung sustain — can crash RB3)"))


def _check_gem_difficulties(tr, name, issues):
    """If a part has any Expert gems, every lower difficulty must be non-empty
    too — selecting an empty difficulty crashes RB3."""
    present = {}
    for diff, (lo, hi) in _DIFF_WINDOWS.items():
        present[diff] = any(_is_on(m) and lo <= m.note <= hi for m in tr)
    if not present["Expert"]:
        return                                  # not a charted gem part
    for diff in ("Easy", "Medium", "Hard"):
        if not present[diff]:
            issues.append(("error",
                           f"{name}: {diff} difficulty has no gems "
                           f"(empty difficulty crashes RB3)"))


def _check_vocals(tr, name, issues):
    """Vocal notes must fall inside a phrase marker, and phrases must not overlap."""
    abs_evts = to_abs(tr)
    phrases = []                                 # (start_tick, end_tick)
    open_t = None
    for e in abs_evts:
        m = e.msg
        if getattr(m, "note", None) not in _VOCAL_PHRASE:
            continue
        if _is_on(m):
            if open_t is not None:
                issues.append(("error", f"{name}: overlapping vocal phrase "
                                        f"markers (can crash the vocal tracker)"))
            open_t = e.abs_tick
        elif _is_off(m) and open_t is not None:
            phrases.append((open_t, e.abs_tick))
            open_t = None
    if not phrases:
        return
    outside = 0
    for e in abs_evts:
        m = e.msg
        n = getattr(m, "note", None)
        if n is None or not (_VOCAL_MIN <= n <= _VOCAL_MAX) or not _is_on(m):
            continue
        if not any(s <= e.abs_tick < en for s, en in phrases):
            outside += 1
    if outside:
        issues.append(("error", f"{name}: {outside} vocal note(s) outside any "
                                f"phrase marker (can crash the vocal tracker)"))


def _measure_spam(mid: mido.MidiFile) -> dict:
    """Measure PP and directed spam metrics from a MIDI's VENUE track.

    Analisa o VENUE track para medir densidade de post-processing e
    directed cuts. Usado internamente para comparar o output do Downcharter
    com o envelope oficial (learn-set de 30 MIDIs).

    Returns:
        pp_events_per_section: list of int — PP events por secção
        pp_filters_per_section: list of int — filtros PP distintos por secção
        directed_consecutive_pct: float (0-1) — % de directed cuts consecutivos
                                   do mesmo tipo
    """
    venue_tr = None
    events_tr = None
    song_end = 0

    for tr in mid.tracks:
        nm = (tr.name or "").strip().upper()
        if nm == "VENUE":
            venue_tr = tr
        elif nm == "EVENTS":
            events_tr = tr
        t = 0
        for msg in tr:
            t += msg.time
        song_end = max(song_end, t)

    # ── Parse sections from EVENTS track ──
    sections: list[tuple[int, int, str]] = []  # (start_tick, end_tick, name)
    if events_tr:
        raw: list[tuple[int, str]] = []
        t = 0
        for msg in events_tr:
            t += msg.time
            txt = getattr(msg, "text", None)
            if txt is not None and msg.type in ("text", "marker"):
                m = _SECTION_RE.search(txt)
                if m:
                    raw.append((t, m.group(1) or m.group(2)))
        raw.sort()
        for i, (tick, name) in enumerate(raw):
            end = raw[i + 1][0] if i + 1 < len(raw) else song_end
            sections.append((tick, end, name))

    if not sections:
        sections.append((0, song_end, "default"))

    # ── Parse VENUE text events ──
    pp_times: list[tuple[int, str]] = []            # (tick, filter_name)
    directed_times: list[tuple[int, str]] = []       # (tick, directed_type)

    if venue_tr:
        t = 0
        for msg in venue_tr:
            t += msg.time
            txt = getattr(msg, "text", None)
            if txt is None:
                continue
            txt = txt.strip()

            ppm = _PP_RE.match(txt)
            if ppm:
                pp_times.append((t, ppm.group(1)))
                continue

            dm = _DIRECTED_RE.match(txt)
            if dm:
                directed_times.append((t, dm.group(1)))

    # ── Group PP by section ──
    pp_per_section = [0] * len(sections)
    pp_filters_per_section: list[set] = [set() for _ in sections]

    for tick, filter_name in pp_times:
        for si, (start, end, _) in enumerate(sections):
            if start <= tick < end:
                pp_per_section[si] += 1
                pp_filters_per_section[si].add(filter_name)
                break

    # ── Directed consecutive same-type ──
    directed_consecutive_pct = 0.0
    if len(directed_times) > 1:
        directed_times.sort()
        same_count = 0
        for i in range(1, len(directed_times)):
            if directed_times[i][1] == directed_times[i - 1][1]:
                same_count += 1
        directed_consecutive_pct = same_count / len(directed_times)

    return {
        "pp_events_per_section": pp_per_section,
        "pp_filters_per_section": [len(s) for s in pp_filters_per_section],
        "directed_consecutive_pct": directed_consecutive_pct,
    }


def validate_rb_midi(mid) -> list[tuple[str, str]]:
    """Run the crash-relevant checks on a finished RB3 notes.mid.

    Returns a list of ``(level, message)`` where level is "error" (will likely
    crash RB3 / be rejected) or "warn" (suspicious but probably loads). Empty
    list == clean. Never raises; never mutates `mid`.
    """
    issues: list[tuple[str, str]] = []

    # 1) Time division must be 480 TPB.
    if mid.ticks_per_beat != 480:
        issues.append(("error", f"time division is {mid.ticks_per_beat} TPB, "
                                f"RB3 requires 480"))

    # 2) [end] event present (else characters freeze in slow-mo at the end).
    has_end = any(getattr(m, "text", "").strip().lower() == "[end]"
                  for tr in mid.tracks for m in tr
                  if m.type in ("text", "marker"))
    if not has_end:
        issues.append(("warn", "no [end] event — characters may freeze at the "
                               "song end"))

    # 3) BEAT track + >= 2 beats of lead-in before the first gem.
    beat_tr = next((tr for tr in mid.tracks
                    if (tr.name or "").strip().upper() == "BEAT"), None)
    first_gem = _first_gem_tick(mid)
    if beat_tr is None:
        issues.append(("warn", "no BEAT track found"))
    elif first_gem is not None:
        lead = sum(1 for e in to_abs(beat_tr)
                   if _is_on(e.msg) and e.abs_tick < first_gem)
        if lead < 2:
            issues.append(("error", f"only {lead} beat(s) before the first gem "
                                    f"(RB3 needs >= 2 beats of lead-in)"))

    # 4) Per-track checks.
    for tr in mid.tracks:
        nm = (tr.name or "").strip().upper()
        if not nm:
            continue
        _check_overlaps(tr, nm, issues)
        if any(nm.startswith(p) for p in _GEM_PARTS):
            _check_gem_difficulties(tr, nm, issues)
        if nm == "PART VOCALS":
            _check_vocals(tr, nm, issues)

    return issues
